### ISSUE TITLE
tracing-futures usage unnecessary

### ISSUE THREAD

**Issue by xd009642** [seanpianka/tracing-layer-slack#4]
From a Discord discussion in tokio discord #tracing channel with Eliza: 

> tracing-futures is still necessary if you need to instrument futures::Stream. tracing-futures is tracing support for the futures crate

This crate mentions it in the docs and brings it in as a dependency but never imports it and doesn't use the futures crate so this seems to be a completely unnecessary dependency and could be removed. 

I'm more than willing to PR this, it's just the project has one contributor and doesn't seem to be very active so figured I'd raise an issue first instead of just a drive-by PR.

**Comment by seanpianka** [comment]
Hey there! I must have entirely missed this issue, my apologies, another symptom of a one-maintainer project 🙂 If you're still even using this crate, feel free to make a PR with this change (or I'll take and make it now, and see if it breaks my specific use-case).

I also released a new version today that removes some extraneous configuration that is no longer needed with the new Slack Apps (now that custom integrations are deprecated).

**Comment by seanpianka** [comment]
I've fixed this in [639f722](https://github.com/seanpianka/tracing-layer-slack/commit/639f722268cdb8c21e49ccd234a505d4317df3c1) which has been released as v0.6.0.
